### ISSUE TITLE
Request is not valid error when deploying skill-events

### ISSUE THREAD

**Issue by marky2coats** [alexa/alexa-cookbook#84] opened 2018-02-13 17:06 UTC
Deploying skill-events with ask is returning a 400 Bad Request exception with message "Error parsing the requested content. Please validate the enums in the request, which is a common cause for this exception."

**Comment by kitingChris** [comment] 2018-02-25 16:52
same here...

**Comment by jakemonton** [comment] 2018-02-27 14:51
Same issue here

**Comment by sethshivam75** [comment] 2018-03-08 09:39
facing the same issue

**Comment by sanketvega** [comment] 2018-03-08 11:25
same here

**Comment by dschuett** [comment] 2018-03-08 13:28
+1 This is frustrating. When can we expect this to be fixed? This has obviously been going on for awhile now.

**Comment by jparnau** [comment] 2018-03-08 18:35
I had this problem with chrome. Try in IE.

**Comment by kitingChris** [comment] 2018-03-08 19:16
IE is not an option

**Comment by streamgao** [comment] 2018-03-13 17:27
same!!!

**Comment by sanketvega** [comment] 2018-03-15 12:43
I was getting same error while trying to create custom model . You can avoid this error temporarily by using old UI console.

**Comment by exe222** [comment] 2018-03-15 21:07
Same issue here.

**Comment by error404notfound** [comment] 2018-03-23 08:13
Is there any solution to this yet?

**Comment by PikkaPikkachu** [comment] 2018-03-25 18:12
Same issue.

**Comment by Tukks** [comment] 2018-03-28 07:06
same issue here

**Comment by Tukks** [comment] 2018-03-28 08:50
Working for me, added this to .ask/config
`"merge": {
        "manifest": {
          "apis": {
            "custom": {
              "endpoint": {
                "uri": "name-of-you-lambda-function"
              }
            }
          }
        }
      }`

**Comment by ricardojover** [comment] 2018-04-01 22:16
I was getting the same error, but in my case it was solved by selecting a valid certificate option for my Endpoint.

**Comment by vignesh1214** [comment] 2018-04-02 23:26
I am getting the same error. Is there any solution to this?

**Comment by error404notfound** [comment] 2018-04-02 23:39
@vignesh1214  I havn't head anything yet but there are office hours webinar tommorrow morning my time, so I hope to get it answered then OR at least have some one look at what it could be!

**Comment by SleepyDeveloper** [comment] 2018-04-04 17:54
In order to track this down, I need to know:

1. Where the error is coming from 
    Ask CLI or Browser (the error message suggests the CLI but I see references to the browser)
2. What content in the cookbook is causing the error (Is the problem with the content, developer portal, cli or a combination) 
3. Steps to reproduce.

Please let me know so I can help resolve this issue.

Thanks,

**Comment by TheDreamSaver** [comment] 2018-04-04 19:14
The issue is coming when we deploy this content in the cookbook : 
https://github.com/alexa/alexa-cookbook/tree/master/context/skill-events

just deploy it and you will see the issue in your ask cli.

**Comment by error404notfound** [comment] 2018-04-04 20:34
HI there 

here  is the verbose explanation of what I do. 

Firstly I have a working AWS account and a working Alexa Console. i insralled the ask cli ( via these insrructions https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html)

 npm version == 5.8.00
node version == v9.7.0

 
1) I clone the  repositry ( I do not change any code at all ) 
 git clone https://github.com/alexa/alexa-cookbook

2 i Initiatialize the ASK CLI

 $ cd alexa/alexa-cookbook/labs/HelloWorld/
$ ask init

it asks for a new user or use default. 
I select default and  prints this
? There is no AWS credential setup yet, do you want to continue the initialization? (Default: False) (y/N) 
I select yes.
and then pops up the login webpage and the following is printed

Warning: Profile: "default" will not be able to deploy lambda functions since no AWS credentials are set up.

Switch to 'Login with Amazon' page...
Tokens fetched and recorded in ask-cli config.
Vendor ID set as ************  ( there is an actual vendor id here but presumed it was bad security to share here ) 

Profile [default] initialized successfully.

 3)  I install the npm dependencies with the below in lambda/custom/ 
$ cd lambda/custom
$ npm install

it does so successfully

4)  i go to the HelloWorld  dir (/alexa-cookbook/labs/HelloWorld) and do 
ask deploy 

i get this
-------------------- Update Skill Project --------------------
Skill Id: amzn1.ask.skill.1367bcb7-5539-4286-8c98-8923883f1e5a
Skill deployment finished.
Call update-model error.
Error code: 400
{
  "message": "Request is not valid.",
  "violations": [
    {
      "message": "Error parsing the requested content. Please validate the input."
    }
  ]
}

i do it again with the debug flag

2018-04-04T20:27:07.314Z] - DEBUG - UPDATE-MODEL
request-id: 8b4bd934-3846-11e8-9aad-c728efb3f841
PUT https://api.amazonalexa.com/v1/skills/amzn1.ask.skill.1367bcb7-5539-4286-8c98-8923883f1e5a/stages/development/interactionModel/locales/en-US
status code: 400 Bad Request

Request headers: {"User-Agent":"ask-cli/1.1.2 Node/v9.7.0","Authorization":"Atza|IwEBIBo1Xv49iM6oyVdhuuTBDf5M6YMxMePbJALKnxDFUKwBaOOlP_Ti1arQ2mFRdFAzf-sfPr3OazAAeasPtmeIwt3pjNIYAt1hZFVgalHurzelq2PDh9AZe6vLSe64qsOX1wzxJAi2BEJObG2Qc-038xcZIfPAoAdLYXCpqh-Ig3IZav17U_KF0mM_K-VFCZC7PDeQ3qMPm-emcYmxQ9KXkmA0AWHYw2IYXyXzP-ToIViBjGqO8gsKjkgDLJ-KvGdbFVKYnKBV-EZp7HQFqw1stcH6npY441GTrW-0wlH1vfYPtxDwouC44SeegBMevQ5fW34BDq8t5ibno1RnJp5AXxf0yPlQ_KkZzzWVwKkQx8PQS11yvV9PwHBlE6GIEf_QUAiG7KrvqS-yMJWhPpqhAzzIwtX3jbRfLNC39mFQ1daKTIZxHFyEYXUIhJyx9Jm4qEuJNjldtAYw0As1uJyryijm3gxIY5-gW7-VCoymzSnkGZwZDSj2Ei9U-VLUo6-JdsWHr-zhwOWHAOMIekWjwi_BUB8cDYtq-tukvoaJwopyZFJiOX9nXVfrdzOvquohIwbnlSsZjWHcAWP2oerHf1UZ","accept":"application/json","content-type":"application/json","content-length":312}

Request body: {"interactionModel":{"languageModel":{"invocationName":"hello world","intents":[{"name":"MyIntent","slots":[],"samples":["hello"]},{"intent":"AMAZON.HelpIntent","slots":[],"samples":[]},{"intent":"AMAZON.StopIntent","slots":[],"samples":[]},{"intent":"AMAZON.CancelIntent","slots":[],"samples":[]}],"types":[]}}}

Response headers: {"server":"Server","date":"Wed, 04 Apr 2018 20:27:07 GMT","content-type":"application/json","content-length":"128","connection":"close","x-amzn-requestid":"8b4bd934-3846-11e8-9aad-c728efb3f841","x-amz-date":"Wed, 04 Apr 2018 20:27:07 GMT","x-amzn-errortype":"BadRequestException:http://internal.amazon.com/coral/com.amazon.alexa.skillmanagement/","vary":"Accept-Encoding,User-Agent"}

Response body: {"message":"Request is not valid.","violations":[{"message":"Error parsing the requested content. Please validate the input."}]}

I tried 'ask deploy -v' and it spits out  1.1.2 , which might be the version number.

I hope this is some help in reproducing the error. I am located in NZ but that shouldn't make any difference. Thank you for your time and please let me know if there is anything I can do to assist. 
( also if I have exposed info here that shouldn't by cutting and pasting from the out put please let me know so I can remove it! ) 

Jennie Stenhouse.

**Comment by SleepyDeveloper** [comment] 2018-04-04 20:53
@TheDreamSaver @error404notfound  Thanks so much! I'll let you know when I've tracked this down and have a fix ready.

**Comment by SleepyDeveloper** [comment] 2018-04-04 22:37
@error404notfound  I've fixed the issue with HelloWorld.

@TheDreamSaver I'm going to fix Skill Events next.

**Comment by SleepyDeveloper** [comment] 2018-04-04 23:06
@TheDreamSaver 

The issue is with the **endpoint** defined within **events**. 

It must be valid. It's a chicken or the egg thing. You don't have an endpoint so you can't provide one but you must provide one for it to deploy, so the solution is to remove the events section of the skill.json file run ask deploy and then paste the JSON snippet into the skill.json file and then paste your ARN that was created when you did ask deploy.

The instructions tell you to copy and paste the JSON snippet, however the file that was checked includes it. I'll be removing the section that breaks ask deploy you'll have to paste in later.

I'll close this issue once I've updated the skill.json file.

**Comment by error404notfound** [comment] 2018-04-05 10:39
@SleepyDeveloper 
so with your fix now is my above step through right? 
I now get this when I deploy. ( I am assuming by the time stamps that it's been updated ) 
( note: when i did the ask init it says Tokens fetched and recorded in ask-cli config. and sets a vendor ID ) 

ask deploy
-------------------- Update Skill Project --------------------
Skill Id: amzn1.ask.skill.248f2975-25f0-4a12-ad8c-65327e2481b5
Skill deployment finished.
Model deployment finished.
[Warn]: Lambda deployment skipped, since AWS credentialsfor profile: [default] is missing. CLI lambda functionalities can be enabled by running `ask init` again to add 'aws_profile' to ASK cli_config
Call enable-skill error.
Error code: 403
{
  "message": "Skill is not ready for enablement.",
  "violations": [
    {
      "message": "Regionalized endpoints must not be empty."
    }
  ]
}

here is the verbose....

2018-04-05T05:12:55.316Z] - DEBUG - ENABLE-SKILL
request-id: ff69c2c3-388f-11e8-bce1-81c2fdd9935e
PUT https://api.amazonalexa.com/v1/skills/amzn1.ask.skill.248f2975-25f0-4a12-ad8c-65327e2481b5/stages/development/enablement
status code: 403 Forbidden

Request headers: {"User-Agent":"ask-cli/1.1.2 Node/v9.7.0","Authorization":"Atza|IwEBIMbje-su12r_aM-uhV43YYB7xTpJT8YqlBIT2BxIgfU0se0h-sGCOBtyPyWAh2K3iTxTrC9RjeczbwrqI76z511T0L-uAc-lqqB5p0CrGDrwNayR2XG8z73Ob79prYynBK8hoPuL_X3dkB7bSeV9rGaJbmiXSbObgn7HdeIMJd5v7JCfgXQwDayUs9_9gQ-fN5d8MGPxNrStkR23b6QnQCIKckgB9nh9I_uF4S_Wf1-BJEa2LX_rcbcxqKs9A6XV4iddRQRVoao8HOLVEFZwI-6IFQVcioR9hZYayE74MBDpuPcckofyVCoulr3qw0qEygCjtsBcZBDvysSzqkEFcE34X5OiNW4QCREYnjNikAIgwN4MqDQc-kGB44tJ0EE2pcLH0kE_e3VnnZ206Clzuo9R_x3gC1jJf4Lf_DjBflR0n4gypSt_Z5kCrPvUR1mjsgVI1YHIgYpzHhO2lhYqu2tnVdr5EJ9J31oeC3iwx_6NpNXJEjmYDouC9QOLN8CaVq2Eq7HY7w7y1qnMMDkFXT27Q5JmBcjBl-w2dC7X24QnyqUdL8zNwpJZwz4GjU8M4hKyrzgqCLgTLNU2a6n3qYiO","content-length":0}

Response headers: {"server":"Server","date":"Thu, 05 Apr 2018 05:12:55 GMT","content-type":"application/json","content-length":"119","connection":"close","x-amzn-requestid":"ff69c2c3-388f-11e8-bce1-81c2fdd9935e","x-amz-date":"Thu, 05 Apr 2018 05:12:55 GMT","x-amzn-errortype":"ForbiddenException:http://internal.amazon.com/coral/com.amazon.alexa.skillmanagement/","vary":"Accept-Encoding,User-Agent"}

Response body: "{\"message\":\"Skill is not ready for enablement.\",\"violations\":[{\"message\":\"Regionalized endpoints must not be empty.\"}]}"




however, there is something odd going on with my aws accounts now, it wouldn't let me log in via the pop up to the account I usually use, it insisted that my password was incorrect.  I went as far as reseting the password for that account so I know that it was being entered correctly. I then made a new aws account and it allowed me to log in with those credentials, how ever when i go to the aws console and select lamda I can create functions but can't save them.  So I am now unable to save in either account... 

thank you for your time with this!

**Comment by TheDreamSaver** [comment] 2018-04-05 13:32
Skill deployed finally. But,
1. No option to edit the skill from the skill builder.
![No option to edit the skill from the skill builder.](https://user-images.githubusercontent.com/21354986/38368726-ad3a8242-3903-11e8-9ec0-0e75feb827d1.png)

2. When I say, "Alexa open my household list", it says "I couldn't find any household list."

What am I doing wrong?

**Comment by SleepyDeveloper** [comment] 2018-04-05 17:51
@TheDreamSaver I discovered that issue yesterday. If you look at the logs it says it can't enable the skill. I'm still trying to figure out what the cause of the problem is. In the mean time to work around the GUI you can click on the measure button and then click on the build button to edit the skill.

**Comment by SleepyDeveloper** [comment] 2018-04-05 18:05
@error404notfound the warning you posted indicates that there's no default profile:

[WARN] Lambda deployment skipped, since AWS credentialsfor profile: [default] is missing. CLI lambda functionalities can be enabled by running ask init again to add 'aws_profile' to ASK cli_config

When you ran `ask init` did you create a new profile or select default? If you you created a new profile without setting it to default, I think you have to specify it manually.

Try running `ask init` again and choose default. If you're on macos/linux it should create a folder called .ask in your home folder which contains a file called cli_config. Below is a sample of what the cli_config file should look like but yours should have some tokens.

```
{
  "profiles": {
    "default": {
      "aws_profile": "default",
      "token": {
        "access_token": "",
        "refresh_token": "",
        "token_type": "bearer",
        "expires_in": 3600,
        "expires_at": "2018-04-05T18:54:57.765Z"
      },
      "vendor_id": "xxxxx"
    }
  }
}
```

**Comment by error404notfound** [comment] 2018-04-09 00:50
@SleepyDeveloper  thanks I have it resolved, the problem was that the ask init was only setting up permissions for the alexa console part so that was working but it didn't set it up for the AWS Cli to deploy to lamda. ( which was my fault as I somehow missed the whole having to set up the AWS CLI ) 
i am now able to deploy!
very exciting! 
however when i go to simulate I get an error

Waiting for simulation response{
  "id": "a349a69e-69b3-41c7-8e45-82340db20194",
  "status": "FAILED",
  "result": {
    "error": {
      "message": "Skill is currently disabled in development stage. Please enable skill in order to call this API."
    }
  }
}


I have found some other people who have had this error. 
( https://forums.developer.amazon.com/questions/97373/skill-is-currently-disabled-in-development-stage-p.html ) but it dosn't look like it was resolved. 

I am so close to being able to have a decent workflow!

**Comment by sonofachamp** [comment] 2018-04-10 19:58
@SleepyDeveloper Any movement/updates on this that you're aware of?

**Comment by Cameron637** [comment] 2018-05-10 18:53
I had this issue and realized that, for my case at least, the "uri" value for "endpoint" was invalid.  I was trying to use the shortcut name for the lambda endpoint (like the one in .ask/config) but this field requires the full ARN.

**Comment by franklin-lobb** [comment] 2019-06-13 07:26
closing due to age

**Closed by franklin-lobb** 2019-06-13 07:26 UTC
